### ISSUE TITLE
Warnings - Animated: 'useNativeDriver'

### ISSUE THREAD

**Issue by dantecarlo** [hrutvikpatel/react-native-character-input#11]
When I finish entering all the entries I receive this warning.
![image](https://user-images.githubusercontent.com/11701529/95705959-28050500-0c1b-11eb-8ca6-3b09ae7ed016.png)

**Comment by hrutvikpatel** [comment]
Just published a slight change. Pull version 1.0.5 and see if that fixes your issue. Not sure if this is related. I wasn't able to recreate the useNativeDriver issue.

**Comment by hrutvikpatel** [comment]
As per #12, someone verified that the library is working for them. For now, I will close this issue. If you still face this problem please let me know and we can figure this out! :)
